# Build ePub
formats:
    - epub
    - htmlzip

build:
    image: latest

python:
    version: 3
    setup_py_install: true
    pip_install: true
    extra_requirements:
        - tests
        - docs